#ifndef _RTL8188EE_FW_BLOBS_H
#define _RTL8188EE_FW_BLOBS_H

#include <stdint.h>
#include <stddef.h>

/*
 * Layout is identical to rtw88's struct rtw88_fw_blob (confirmed generic —
 * name/data/compressed_size/original_size, nothing rtw88-specific in the
 * struct itself). Given its own struct name and array name here, both
 * distinct from rtw88's, so the two can coexist in a build that ends up
 * linking both compat layers into related targets without a duplicate-
 * symbol conflict. Redeclared rather than #include "fw_blobs.h" so this
 * header has no dependency on Feixiao's rtw88-side compat tree — keeps
 * RTL8188EE's build inputs self-contained per the project's stated
 * separation goal.
 *
 * If the two struct shapes ever need to diverge, that's an intentional
 * decision to make then, not now — kept identical today deliberately.
 */
struct rtl8188ee_fw_blob {
    const char    *name;
    const uint8_t *data;           /* zlib-compressed */
    size_t         compressed_size;
    size_t         original_size;
};

/* Null-terminated table generated by gen_fw_blobs_rtl8188ee.py */
extern const struct rtl8188ee_fw_blob rtl8188ee_fw_blobs[];

#endif /* _RTL8188EE_FW_BLOBS_H */
