/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
 * rtl8188ee_firmware.c — firmware loading for rtl8188ee macOS port.
 *
 * Mirrors rtl8188ee_firmware.c's confirmed structure function-for-function
 * (zlib allocators, decompress-on-load, embedded-blob lookup), pointed at
 * a separate rtl8188ee_fw_blobs[] table generated by
 * gen_fw_blobs_rtl8188ee.py instead of rtl8188ee's gen_fw_blobs.py — see that
 * script's header comment for why it was forked rather than parameterized.
 *
 * IMPORTANT — naming collision this file avoids, not yet a resolved
 * build-target separation:
 *   rtl8188ee_firmware.c defines request_firmware_nowait(), release_firmware(),
 *   and rtl8188ee_load_firmware_sync() (confirmed by direct read; the
 *   linux/firmware.h comment claiming these live in rtl8188ee_compat.c is
 *   stale — grep against rtl8188ee_compat.c for both symbols returns empty).
 *   This file's equivalents are prefixed rtl8188ee_ specifically so they
 *   don't collide by name if both files ever end up compiled into the
 *   same target. This is a name-collision workaround, NOT the same thing
 *   as the actual build-target decision still open per the handover
 *   (item 25 / findings.md Section 55.6, the mac80211-function collision
 *   in rtlwifi_compat.c) — that decision governs whether rtl8188ee ends
 *   up in a separate Xcode target at all, and still needs to be made.
 *
 *   Whatever rtlwifi's own compat linux/firmware.h ends up looking like,
 *   its request_firmware() inline needs to call
 *   rtl8188ee_load_firmware_sync() below — not rtl8188ee_load_firmware_sync()
 *   — or it will link against the wrong (rtl8188ee-chip) blob table. That
 *   header doesn't exist yet for rtlwifi; flagging the seam here rather
 *   than wiring it silently once it does.
 *
 * Compiled WITHOUT Linux compat headers to avoid type conflicts, same as
 * rtl8188ee_firmware.c.
 */
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include <IOKit/IOLib.h>
#include <libkern/zlib.h>

#include "fw_blobs_rtl8188ee.h"

/*
 * Must match linux/firmware.h's struct firmware field order (size then
 * data) exactly, same as rtl8188ee_firmware.c's private definition.
 * _alloc_size is a private trailer used only by release_firmware().
 */
struct firmware {
    size_t         size;
    const uint8_t *data;
    size_t         _alloc_size;  /* bytes passed to IOMalloc for data */
};

/* ------------------------------------------------------------------ */
/*  zlib allocators — identical logic to rtl8188ee_firmware.c's           */
/* ------------------------------------------------------------------ */

typedef struct z_mem {
    uint32_t alloc_size;
    uint8_t  data[0];
} z_mem;

static voidpf rtl8188ee_zcalloc(voidpf opaque, uInt items, uInt size)
{
    (void)opaque;
    uint32_t alloc = (uint32_t)(items * size) + (uint32_t)sizeof(z_mem *);
    z_mem *zm = (z_mem *)IOMalloc(alloc);
    if (!zm) return Z_NULL;
    zm->alloc_size = alloc;
    return (voidpf)zm->data;
}

static void rtl8188ee_zcfree(voidpf opaque, voidpf ptr)
{
    (void)opaque;
    if (!ptr) return;
    z_mem *zm = (z_mem *)((uint32_t *)ptr - 1);
    IOFree(zm, zm->alloc_size);
}

/* ------------------------------------------------------------------ */
/*  Decompress one blob — identical logic to rtl8188ee_firmware.c's       */
/* ------------------------------------------------------------------ */

static int rtl8188ee_decompress(uint8_t *dest, uint32_t *dest_len,
                                 const uint8_t *src, uint32_t src_len)
{
    z_stream zs;
    zs.next_in   = (Bytef *)src;
    zs.avail_in  = src_len;
    zs.next_out  = (Bytef *)dest;
    zs.avail_out = *dest_len;
    zs.zalloc    = rtl8188ee_zcalloc;
    zs.zfree     = rtl8188ee_zcfree;
    zs.opaque    = Z_NULL;

    int err = inflateInit(&zs);
    if (err != Z_OK) {
        IOLog("rtl8188ee: inflateInit error %d\n", err);
        return err;
    }

    err = inflate(&zs, Z_FINISH);
    if (err != Z_STREAM_END) {
        IOLog("rtl8188ee: inflate error %d (avail_in=%u avail_out=%u)\n",
              err, zs.avail_in, zs.avail_out);
        inflateEnd(&zs);
        return err;
    }

    *dest_len = (uint32_t)zs.total_out;
    err = inflateEnd(&zs);
    return (err == Z_OK) ? 0 : err;
}

/* ------------------------------------------------------------------ */
/*  Blob lookup + decompress                                          */
/* ------------------------------------------------------------------ */

static struct firmware *load_fw_from_blob(const char *base)
{
    for (int i = 0; rtl8188ee_fw_blobs[i].name; i++) {
        if (strcmp(rtl8188ee_fw_blobs[i].name, base) != 0)
            continue;

        const struct rtl8188ee_fw_blob *b = &rtl8188ee_fw_blobs[i];

        /* 4x compressed size — same generous bound as rtl8188ee_firmware.c */
        size_t alloc = b->compressed_size * 4;
        uint32_t out_len = (uint32_t)alloc;
        uint8_t *buf = (uint8_t *)IOMalloc(alloc);
        if (!buf) {
            IOLog("rtl8188ee: OOM for %s (%zu bytes)\n", base, alloc);
            return NULL;
        }

        if (rtl8188ee_decompress(buf, &out_len,
                                  b->data, (uint32_t)b->compressed_size) != 0) {
            IOLog("rtl8188ee: decompress failed for %s\n", base);
            IOFree(buf, alloc);
            return NULL;
        }

        struct firmware *fw = (struct firmware *)IOMallocZero(sizeof(*fw));
        if (!fw) {
            IOFree(buf, alloc);
            return NULL;
        }
        fw->data        = buf;
        fw->size        = out_len;   /* actual bytes from total_out */
        fw->_alloc_size = alloc;     /* original IOMalloc size for IOFree */
        IOLog("rtl8188ee: firmware %s loaded from blob (%u bytes)\n",
              base, out_len);
        return fw;
    }

    IOLog("rtl8188ee: firmware %s not in embedded blobs\n", base);
    return NULL;
}

static struct firmware *load_fw(const char *name)
{
    const char *base = name;
    for (const char *p = name; *p; p++)
        if (*p == '/') base = p + 1;

    return load_fw_from_blob(base);
}

/* ------------------------------------------------------------------ */
/*  Public API — signatures match linux/firmware.h; names prefixed    */
/*  rtl8188ee_ to avoid colliding with rtl8188ee_firmware.c's symbols     */
/*  by name alone (see file header comment — this is a naming         */
/*  workaround, not the still-open build-target separation decision). */
/* ------------------------------------------------------------------ */

struct module;
struct device;

int rtl8188ee_request_firmware_nowait(struct module *module, int uevent,
                                       const char *name, struct device *device,
                                       unsigned int gfp, void *context,
                                       void (*cont)(const struct firmware *fw, void *ctx))
{
    (void)module; (void)uevent; (void)device; (void)gfp;
    if (!cont) return -22;
    struct firmware *fw = load_fw(name);
    cont(fw, context);
    return 0;
}

void rtl8188ee_release_firmware(const struct firmware *fw)
{
    if (!fw) return;
    if (fw->data) IOFree((void *)fw->data, fw->_alloc_size);
    IOFree((void *)fw, sizeof(*fw));
}

/*
 * rtlwifi's own request_firmware() (its future linux/firmware.h) needs to
 * call THIS function, not rtl8188ee_load_firmware_sync() — confirmed by direct
 * read that rtl8188ee's request_firmware() inline calls straight through to
 * rtl8188ee_load_firmware_sync() synchronously despite the "nowait" naming
 * elsewhere in that file. rtlwifi's compat firmware.h doesn't exist yet;
 * flagging the seam now so it's wired correctly when it's written.
 */
int rtl8188ee_load_firmware_sync(const char *name, const struct firmware **fw_out)
{
    *fw_out = load_fw(name);
    return *fw_out ? 0 : -2;
}

void rtl8188ee_set_fw_dir(const char *dir) { (void)dir; }
void rtl8188ee_find_fw_dir(void) {}
