#!/usr/bin/env python3
# gen_fw_blobs_rtl8188ee.py — generate fw_blobs.c for RTL8188EE from firmware/*.bin
#
# Forked from Feixiao/scripts/gen_fw_blobs.py (findings.md Section 56).
# Reason for the fork rather than parameterizing the original: the emitted
# array name was hardcoded as `rtw88_fw_blobs`, colliding at link time with
# rtw88's own table of the same name if both are compiled into one target
# (same duplicate-symbol class of problem as rtlwifi_compat.c vs
# rtw88_compat.c, see rtlwifi_compat.h's build-target warning). Forking
# keeps RTL8188EE-specific build tooling separate from Feixiao's existing
# rtw88 scripts, per the project's stated organization goals, at the cost
# of two near-identical scripts to keep in sync if the blob format changes.
#
# Only change from the original: the emitted table symbol is
# `rtl8188ee_fw_blobs` instead of `rtw88_fw_blobs`, matching the
# `extern` declared in rtl8188ee_fw_blobs.h (NOT the original fw_blobs.h,
# which still declares `rtw88_fw_blobs` and is intentionally left untouched).
#
# Usage: python3 gen_fw_blobs_rtl8188ee.py <fw_dir> <output.c>

import sys, os, zlib

fw_dir  = sys.argv[1]
out_c   = sys.argv[2]

bins = sorted(f for f in os.listdir(fw_dir) if f.endswith('.bin'))
if not bins:
    # No firmware — emit an empty table so the build still works.
    # TODO: rtl8188efw.bin is not yet present in any firmware/ directory
    # in this repo (per rtl8188ee_handover.txt open items) — this branch
    # is expected to be hit until that blob is obtained from linux-firmware.
    with open(out_c, 'w') as f:
        f.write('/* No firmware blobs — add rtl8188efw.bin to firmware-rtl8188ee/ and rebuild */\n')
        f.write('#include "rtl8188ee_fw_blobs.h"\n')
        f.write('const struct rtl8188ee_fw_blob rtl8188ee_fw_blobs[] = { { 0, 0, 0, 0 } };\n')
    sys.exit(0)

lines = []
lines.append('/* Auto-generated by gen_fw_blobs_rtl8188ee.py — do not edit */')
lines.append('#include <stdint.h>')
lines.append('#include <stddef.h>')
lines.append('#include "rtl8188ee_fw_blobs.h"')
lines.append('')

entries = []
for name in bins:
    path = os.path.join(fw_dir, name)
    raw  = open(path, 'rb').read()
    comp = zlib.compress(raw, 9)

    sym = 'fw_' + name.replace('.', '_').replace('-', '_')
    entries.append((name, sym, len(comp), len(raw)))

    # emit as C array, 16 bytes per line
    lines.append(f'static const uint8_t {sym}[] = {{')
    for i in range(0, len(comp), 16):
        chunk = comp[i:i+16]
        hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'    {hex_str},')
    lines.append('};')
    lines.append('')

lines.append('const struct rtl8188ee_fw_blob rtl8188ee_fw_blobs[] = {')
for name, sym, csz, osz in entries:
    lines.append(f'    {{ "{name}", {sym}, {csz}, {osz} }},')
lines.append('    { 0, 0, 0, 0 }')
lines.append('};')
lines.append('')

with open(out_c, 'w') as f:
    f.write('\n'.join(lines) + '\n')

total_orig = sum(e[3] for e in entries)
total_comp = sum(e[2] for e in entries)
print(f'  GEN  {out_c}: {len(bins)} blobs, '
      f'{total_orig//1024}KB -> {total_comp//1024}KB compressed')
